# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package.json ./

# If a lockfile exists, uncomment the following line
# COPY package-lock.json ./

# Copy all source files
COPY . .

# Install dependencies without executing any scripts
RUN npm install --ignore-scripts

# Build the application
RUN npm run build

# Expose port 3000 (if applicable)
EXPOSE 3000

# Default command to run the MCP server
ENTRYPOINT ["node", "bin/cli.js", "--token=dummy", "--url=http://localhost:3000"]
